spring:
  application:
    name: preky
  datasource:
    url: jdbc:mysql://localhost:3306/prekydb?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  #jpa:
    #hibernate:
      #ddl-auto: update
    #show-sql: true
    #database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8899
  context-path: /preky
